import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const client = await readFile(new URL('../src/client.js', import.meta.url), 'utf8')

test('client adopts the one native conversation declaration and reuses its inner slots', () => {
  // The native entry's seat moved to `main.conversation` in DSH 0.1.6, so the
  // plugin resolves it instead of naming one seat.
  assert.match(client, /const conversationSlots = \['main\.conversation', 'conversation'\]/)
  assert.match(client, /const slot = resolveConversationSlot\(\)/)
  assert.match(client, /core\.entries\(slot\)/)
  assert.match(client, /unsubscribers = conversationSlots\.map\(slot => core\.subscribe\(slot, reconcile\)\)/)
  assert.match(client, /nativeEntry\.component = ParallelConversation/)
  assert.match(client, /core\.register\(\{ name: slot, priority: -100 \}, \(\) => null\)/)
  for (const slot of ['conversation.session', 'conversation.composer.bar']) {
    assert.match(client, new RegExp(slot.replaceAll('.', '\\.')))
  }
  assert.match(client, /NativeConversationRoot = previous/)
  assert.match(client, /slots\.inject\('conversation\.session\.header\.actions'/)
  assert.match(client, /slots\.inject\('conversation\.session\.header\.utilities'/)
  assert.match(client, /h\(NativeConversationRoot, props\)/)
  assert.match(client, /h\(SideNativeConversation/)
  assert.doesNotMatch(client, /shell\.overlay|name: 'details'|openDetails|closeDetails/)
})

test('client contains the requested delete-or-keep and selection entry interactions', () => {
  assert.match(client, /删除并关闭/)
  assert.match(client, /保留对话/)
  assert.match(client, /引用到侧聊/)
  assert.match(client, /function installSidePromptProjection/)
  assert.match(client, /conversationService\.sendSession = wrapped/)
  assert.match(client, /const projectedText = String\(text\)\.trim\(\) === ''/)
  assert.match(client, /> 主对话选文/)
  assert.doesNotMatch(client, /slash\/input-insert-reference/)
  assert.doesNotMatch(client, /trigger: '@'/)
  assert.doesNotMatch(client, /side_chat_selected_text/)
  assert.doesNotMatch(client, /请围绕主对话中选中的这段文字/)
  assert.doesNotMatch(client, /sideChat\.send|mergeMessages|assistantBody/)
})

test('selected text actions stay inside the viewport and remain visibly attached to side chat', () => {
  assert.match(client, /function SelectionActions/)
  assert.match(client, /window\.visualViewport/)
  assert.match(client, /width - size\.width - edge/)
  assert.match(client, /ReactDOM\.createPortal\(h\('div'/)
  assert.match(client, /aria-label': '选中文本操作'/)
  assert.match(client, /function appendSelection/)
  assert.match(client, /function storedSelections/)
  assert.match(client, /function persistSelections/)
  assert.match(client, /function SideSelectionQuote/)
  assert.match(client, /function SideSelectionDock\(\{ session, input, inputActions \}\)/)
  assert.match(client, /name: 'conversation\.input\.dock'/)
  assert.match(client, /id: 'side-chat-selection-context'/)
  assert.match(client, /data-side-chat-selection-dock/)
  assert.match(client, /\$\{selections\.length\} 条引用/)
  assert.match(client, /aria-label': '已引用的主对话选文'/)
  assert.match(client, /className: 'dsh-sc-quote-details'/)
  assert.match(client, /ReactDOM\.createPortal\(details, document\.body\)/)
  assert.match(client, /aria-label': '移除全部引用'/)
  assert.match(client, /aria-label': `移除第 \$\{index \+ 1\} 条引用`/)
  assert.match(client, /}, '移除此条'\)/)
  assert.match(client, /REFERENCE_MIGRATION_KEY/)
  assert.match(client, /if \(legacyPlaceholder \|\| legacyProjection\) inputActions\.setDraft\(''\)/)
  assert.doesNotMatch(client, /data-dsh-side-synthetic-only/)
  assert.doesNotMatch(client, /textarea\.setSelectionRange/)
  assert.doesNotMatch(client, /input\.occurrences/)
  assert.match(client, /const selections = appendSelection/)
  assert.match(client, /const selections = Array\.isArray\(owner\?\.side\.selections\)/)
  assert.match(client, /persistSelections\(owner\.side\.sideId, remaining\)/)
  assert.doesNotMatch(client, /SIDE_SELECTION_LABEL/)
  assert.match(client, /background:var\(--dsw-alias-bg-layer-1,var\(--dsw-specific-input-major,#fff\)\)/)
  assert.doesNotMatch(client, /dsh-sc-selection-preview/)
})

test('settings expose enablement and native preset choices', () => {
  assert.match(client, /id: 'side-chat'/)
  assert.match(client, /name: 'settings\.section'/)
  assert.match(client, /标准模式/)
  assert.match(client, /PTC 模式/)
  assert.match(client, /极简模式/)
  assert.match(client, /创造模式/)
  assert.match(client, /每次询问/)
  assert.match(client, /始终保留/)
  assert.match(client, /始终删除/)
  assert.match(client, /closeBehavior/)
  assert.doesNotMatch(client, /showModelSelector|data-show-model-selector/)
  assert.doesNotMatch(client, /显示模型选择/)
})

test('side session uses framework BindingContext provider and arbitrary provideInfo', () => {
  assert.match(client, /SessionProvider\(\{ empty:/)
  assert.match(client, /sessionsService\?\.provideInfo\?\./)
  assert.match(client, /h\(BindingProvider, \{ value: projectedSideInfo/)
  assert.match(client, /sessionsService\?\.binding\?\.\(sideId\)\?\.session/)
  assert.match(client, /session\.open\(\)/)
  assert.match(client, /source\.subscribe\(listener\)/)
  assert.match(client, /function projectSideProvideInfo/)
  assert.match(client, /getSnapshot: \(\) => projectSideSession\(source\.getSnapshot\(\)\)/)
  assert.match(client, /composerPhase: 'active'/)
})

test('parallel shell aligns, resizes, hides and restores the native side conversation', () => {
  assert.match(client, /data-conversation-scroll.*data-composer-seat/)
  assert.match(client, /dsh-sc-column-side:not\(:has\(\[data-slot="conversation\.composer\.dock"\]>\*\)\)\{padding-bottom:24px\}/)
  assert.match(client, /role: 'separator'/)
  assert.match(client, /aria-label': '调整主对话与侧聊宽度'/)
  assert.match(client, /sideRatio/)
  assert.match(client, /label: '隐藏侧聊'/)
  assert.match(client, /label: '关闭侧聊'/)
  assert.match(client, /label: '显示侧聊'/)
  assert.match(client, /function SideChatIcon/)
  assert.match(client, /Same message-plus glyph used by DSH/)
  assert.doesNotMatch(client, /dsh-sc-side-actions/)
  assert.match(client, /\.dsh-sc-resizer\{position:relative;z-index:1;/)
  assert.match(client, /body:has\(\[role="dialog"\]/)
  assert.match(client, /name: 'conversation\.session\.header\.utilities'/)
  assert.match(client, /id: 'side-chat-controls'/)
  assert.match(client, /function useBetterSidebarToggleCluster/)
  assert.match(client, /data-side-chat-corner-entry/)
  assert.match(client, /dsh-sc-corner-entry/)
  assert.match(client, /body:has\(\.dsh-sc-corner-entry\).*--dsh-sc-header-reserve/)
  assert.match(client, /\.dsh-sc-column-main \[data-phase\] header/)
  assert.match(client, /column\?\.querySelector\('\[data-phase\] header'\)/)
  assert.match(client, /function BetterSidebarCornerEntry/)
  assert.match(client, /function useBetterSidebarHeaderReserve/)
  assert.match(client, /\.dsh-sc-column-side \[data-phase\] header/)
  assert.match(client, /renderedProbe \/ 100/)
  assert.match(client, /headerRect\.right - entryRect\.left \+ 8/)
  assert.match(client, /new ResizeObserver\(schedule\)/)
  assert.match(client, /ReactDOM\.createPortal/)
  assert.match(client, /\.dsh-sc-modal-backdrop\{position:fixed;inset:0;z-index:2147483647/)
})

test('parallel shell adapts to its actual container without widening narrow hosts', () => {
  assert.match(client, /container-name:dsh-side-chat;container-type:inline-size/)
  assert.match(client, /\.dsh-sc-column\{[^}]*width:100%;max-width:100%;min-width:0/)
  assert.match(client, /\.dsh-sc-root-split \.dsh-sc-column-main,\.dsh-sc-root-split \.dsh-sc-resizer\{display:none\}/)
  assert.match(client, /@container dsh-side-chat \(min-width:981px\)/)
  assert.match(client, /\.dsh-sc-root-split \.dsh-sc-column-side\{flex:0 0 var\(--dsh-sc-side-width,50%\);width:auto;max-width:none\}/)
  assert.match(client, /data-side-chat-layout': sideVisible \? 'split' : 'single'/)
  assert.doesNotMatch(client, /min-width:440px/)
  assert.doesNotMatch(client, /@media\(max-width:980px\)/)
})

test('Better Sidebar and side chat use mutually exclusive split docks', () => {
  assert.match(client, /function betterSidebarPanelOpen/)
  assert.match(client, /\[data-dsh-better-sidebar\]/)
  assert.match(client, /data-dsh-sidebar-collapsed/)
  assert.match(client, /\[class\$="_panel"\]/)
  assert.match(client, /useBetterSidebarPanelOpen\(sideVisible\)/)
  assert.match(client, /function closeBetterSidebarPanel/)
  assert.match(client, /if \(sideVisible && betterSidebarOpen\) closeBetterSidebarPanel\(\)/)
  assert.match(client, /const divider = sideVisible/)
  assert.match(client, /data-side-chat-layout': sideVisible \? 'split' : 'single'/)
  assert.doesNotMatch(client, /data-side-chat-better-sidebar-mode/)
  assert.doesNotMatch(client, /dsh-sc-better-overlay/)
  assert.match(client, /function useBetterSidebarAutoHide/)
  assert.match(client, /打开 Sidebar 时自动收起侧聊/)
  assert.match(client, /if \(!betterSidebarPanelOpen\(\)\) patchSide\(parentId, \{ hidden: true \}\)/)
  assert.match(client, /patchSide\(parentId, \{ hidden: true \}\)/)
})

test('side pane is scoped to its owning main session', () => {
  assert.match(client, /sides: new Map\(\)/)
  assert.match(client, /const sideState = state\.sides\.get\(props\.sessionId\)/)
  assert.match(client, /const ownsSide = state\.enabled && sideState !== undefined/)
  assert.match(client, /const sideVisible = ownsSide && sideState\.hidden !== true/)
  assert.match(client, /const sideId = sideState\?\.sideId \?\? null/)
  assert.match(client, /const divider = sideVisible/)
  assert.match(client, /if \(sideVisible\)/)
})

test('multiple main conversations retain independent side sessions', () => {
  assert.match(client, /const sides = new Map\(uiState\.sides\)/)
  assert.match(client, /sides\.set\(parentId, Object\.freeze\(side\)\)/)
  assert.match(client, /const side = state\.sides\.get\(sessionId\)/)
  assert.match(client, /function findSideOwner\(state, sideId\)/)
  assert.match(client, /choose\('keep'\)/)
  assert.match(client, /choose\('delete'\)/)
  assert.match(client, /记住此选择/)
  assert.match(client, /sideInfo\?\.sessionId === sideId/)
})
